notifications:
  email: false
language: node_js
node_js:
  - "lts/*"
install:
  - npm install
script:
  - npm run lint || true # informational only, ignore errors
  - npm run test-backend
  - npm run fetch-kernel
  - npm run render-kernel
  - npm run test-kernel
  - npm run test-frontend
